env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:import/recommended
  - plugin:jsx-a11y/recommended
  - airbnb-base
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - jsx-a11y
rules:
  object-curly-newline: off
  import/extensions: 0
  import/no-unresolved: 0
  react/prop-types: 0
  no-console: 0
  # react/react-in-jsx-scope: 0
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  react/function-component-definition:
    [2, { 'namedComponents': 'arrow-function' }]
  react/jsx-filename-extension: [1, { 'extensions': ['.js', '.jsx'] }]
